name: CI&CD
on: [push, workflow_dispatch]
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      #- name: install deps
       # run: yarn install
    #  - name: my docker
     #   uses: docker://alpine:3.8
      - name: test
        run: yarn run test
   #   - name: tests
    #    run: yarn test
